---
- name: Install bitlbee
  xbps:
    name: bitlbee
    state: present

- name: Enable bitlbee
  file:
    src: /etc/sv/bitlbee
    dest: /var/service/bitlbee
    state: link

- name: Install firewall rules
  copy:
    src: bitlbee.rules
    dest: /etc/iptables.d/
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
